
import java.awt.Graphics;
import java.util.ArrayList;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DRACOX
 */
public class DotGamePanel extends javax.swing.JPanel {

    /**
     * Creates new form DotGamePanel
     */
    ArrayList<Dots> myDots = new ArrayList();
    ArrayList<Lines> myLines = new ArrayList();
    public void paintComponent(Graphics g){
        for(int i = 0; i< myDots.size(); i++)
        {
            myDots.get(i).createDot(g);
            
        }
    }
    
    public DotGamePanel() {
        initComponents();
        
       
        
        for(int i = 100; i < 600; i = i+100)
        {
            for(int j = 100; j < 600; j = j+100)
            {
                Dots myDot = new Dots(i,j);
                myDots.add(myDot);
               // System.out.println(i + " " +j);
            }
        }
        
        //Lines myLine = new Lines(myDots.get(0), myDots.get(3));
        
       /* for (int i = 0; i< 5; i= i++)
        {
            for( int j = 0; j <3; j = j++)
            {
            Lines myLine = new Lines(myDots.get(i+j),myDots.get(i+j+1));
            myLines.add(myLine);
            }
        }*/
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
