/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foursquare;

import java.awt.CardLayout;
import java.awt.Container;

/**
 *
 * @author JSS5783
 
 (Client)
 Client program. Player logs in (jpLogIn), then waits for match-making (jpLobby), and plays a match (jpMatch).
 Player returns to jpLobby upon conclusion of a match (win, lose, draw, or disconnect).
 Player returns to jpLogIn on disconnecting, voluntarily or otherwise.
 
 ----------[CHANGELOG]----------
 2018/04/10 -     GUI built in GUI builder now, with custom components manually added since the drag-and-drop into the GUI builder doesn't work.
                  Renamed variables to use clearer names:
                      jfClientLobby -> jfClient
 *                      jpli -> jpLogin1
 *                      jpl -> jpLobby1
 *                      jpm -> jpMatch1
 *                  Added comments. -JSS5783
 * 
 * 2018/03/25 -     Created. -JSS5783
 */
public class jfClient extends javax.swing.JFrame {
    
    //declaration
    private jpLogIn jpLogin1;
    private jpLobby jpLobby1;
    private jpMatch jpMatch1;
    private static CardLayout cl;
    private static Container cClient;

    /**
     * Creates new form ClientLobby
     */
    public jfClient()
    {
        initComponents();
        
        //initialization
        jpLogin1 = new jpLogIn();
        jpMatch1  = new jpMatch();
        jpLobby1  = new jpLobby();
        cl  = new CardLayout();
        cClient = new Container();
        
        //set layout to CardLayout
        cClient = this.getContentPane();
        cClient.setLayout(cl);
        
        //registration
        this.add(jpLogin1);
        this.add(jpLobby1);
        this.add(jpMatch1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Project 4Square (CLIENT)");
        setMinimumSize(new java.awt.Dimension(960, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfClient().setVisible(true);
            }
        });
    }
    
    /**
     * Changes to the next panel.
     * Panel order: Login -> lobby -> match -> login.
     */
    public static void nextCard()
    {
        cl.next(cClient);
    }   //END nextCard()
    
    
    
    /**
     * Changes to the previous panel.
     * Panel order: Match -> lobby -> login -> match.
     */
    public static void previousCard()
    {
        cl.previous(cClient);
    }   //END previousCard()

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
