/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foursquare;

/**
 *
 * @author jss5783
 * 
 * ----------[CHANGELOG]----------
 * 2018/04/23 -     Finished designing GUI.
 *                  Added ServerConnection server. -JSS5783
 * 
 * 2018/04/18 -     Continued designing GUI.    -JSS5783
 * 
 * 2018/04/16 -     Created. -JSS5783
 */
public class jfServer extends javax.swing.JPanel {

    /**
     * Creates new form jfServer
     */
    public jfServer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnStartStopServer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jpnlConnection3 = new javax.swing.JPanel();
        jlblConnection3UsernameUserID = new javax.swing.JLabel();
        jlblConnection3Status = new javax.swing.JLabel();
        jbtnConnection3Disconnect = new javax.swing.JButton();
        jbtnConnection3ForceWin = new javax.swing.JButton();
        jpnlConnection4 = new javax.swing.JPanel();
        jlblConnection4UsernameUserID = new javax.swing.JLabel();
        jlblConnection4Status = new javax.swing.JLabel();
        jbtnConnection4Disconnect = new javax.swing.JButton();
        jbtnConnection4ForceWin = new javax.swing.JButton();
        jpnlConnection2 = new javax.swing.JPanel();
        jlblConnection2UsernameUserID = new javax.swing.JLabel();
        jlblConnection2Status = new javax.swing.JLabel();
        jbtnConnection2Disconnect = new javax.swing.JButton();
        jbtnConnection2ForceWin = new javax.swing.JButton();
        jpnlConnection1 = new javax.swing.JPanel();
        jlblConnection1UsernameUserID = new javax.swing.JLabel();
        jlblConnection1Status = new javax.swing.JLabel();
        jbtnConnection1Disconnect = new javax.swing.JButton();
        jbtnConnection1ForceWin = new javax.swing.JButton();

        jbtnStartStopServer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnStartStopServer.setText("Start Server");
        jbtnStartStopServer.setPreferredSize(new java.awt.Dimension(100, 35));
        jbtnStartStopServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnStartStopServerActionPerformed(evt);
            }
        });

        jPanel1.setBackground(PVar.BACKGROUND_COLOR);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Connections", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jpnlConnection3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Connection 3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jlblConnection3UsernameUserID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblConnection3UsernameUserID.setText("Username (User ID): 12345678");

        jlblConnection3Status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblConnection3Status.setText("Status: Lobby (cooldown)");

        jbtnConnection3Disconnect.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnConnection3Disconnect.setText("Disconnect");
        jbtnConnection3Disconnect.setPreferredSize(new java.awt.Dimension(100, 35));

        jbtnConnection3ForceWin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnConnection3ForceWin.setText("Force Win");
        jbtnConnection3ForceWin.setPreferredSize(new java.awt.Dimension(100, 35));

        javax.swing.GroupLayout jpnlConnection3Layout = new javax.swing.GroupLayout(jpnlConnection3);
        jpnlConnection3.setLayout(jpnlConnection3Layout);
        jpnlConnection3Layout.setHorizontalGroup(
            jpnlConnection3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlConnection3Layout.createSequentialGroup()
                .addGroup(jpnlConnection3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnConnection3ForceWin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnConnection3Disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnlConnection3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpnlConnection3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jlblConnection3UsernameUserID))
                        .addGroup(jpnlConnection3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jlblConnection3Status))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlConnection3Layout.setVerticalGroup(
            jpnlConnection3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlConnection3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblConnection3UsernameUserID)
                .addGap(18, 18, 18)
                .addComponent(jlblConnection3Status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jbtnConnection3ForceWin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnConnection3Disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpnlConnection4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Connection 4", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jlblConnection4UsernameUserID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblConnection4UsernameUserID.setText("Username (User ID): 12345678");

        jlblConnection4Status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblConnection4Status.setText("Status: Lobby (cooldown)");

        jbtnConnection4Disconnect.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnConnection4Disconnect.setText("Disconnect");
        jbtnConnection4Disconnect.setPreferredSize(new java.awt.Dimension(100, 35));

        jbtnConnection4ForceWin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnConnection4ForceWin.setText("Force Win");
        jbtnConnection4ForceWin.setPreferredSize(new java.awt.Dimension(100, 35));

        javax.swing.GroupLayout jpnlConnection4Layout = new javax.swing.GroupLayout(jpnlConnection4);
        jpnlConnection4.setLayout(jpnlConnection4Layout);
        jpnlConnection4Layout.setHorizontalGroup(
            jpnlConnection4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlConnection4Layout.createSequentialGroup()
                .addGroup(jpnlConnection4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlConnection4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblConnection4UsernameUserID))
                    .addGroup(jpnlConnection4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblConnection4Status))
                    .addGroup(jpnlConnection4Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jpnlConnection4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnConnection4ForceWin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnConnection4Disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jpnlConnection4Layout.setVerticalGroup(
            jpnlConnection4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlConnection4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblConnection4UsernameUserID)
                .addGap(18, 18, 18)
                .addComponent(jlblConnection4Status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jbtnConnection4ForceWin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnConnection4Disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpnlConnection2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Connection 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jlblConnection2UsernameUserID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblConnection2UsernameUserID.setText("Username (User ID): 12345678");

        jlblConnection2Status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblConnection2Status.setText("Status: Lobby (cooldown)");

        jbtnConnection2Disconnect.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnConnection2Disconnect.setText("Disconnect");
        jbtnConnection2Disconnect.setPreferredSize(new java.awt.Dimension(100, 35));

        jbtnConnection2ForceWin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnConnection2ForceWin.setText("Force Win");
        jbtnConnection2ForceWin.setPreferredSize(new java.awt.Dimension(100, 35));

        javax.swing.GroupLayout jpnlConnection2Layout = new javax.swing.GroupLayout(jpnlConnection2);
        jpnlConnection2.setLayout(jpnlConnection2Layout);
        jpnlConnection2Layout.setHorizontalGroup(
            jpnlConnection2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlConnection2Layout.createSequentialGroup()
                .addGroup(jpnlConnection2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnConnection2ForceWin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnConnection2Disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnlConnection2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpnlConnection2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jlblConnection2UsernameUserID))
                        .addGroup(jpnlConnection2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jlblConnection2Status))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jpnlConnection2Layout.setVerticalGroup(
            jpnlConnection2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlConnection2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblConnection2UsernameUserID)
                .addGap(18, 18, 18)
                .addComponent(jlblConnection2Status)
                .addGap(18, 18, 18)
                .addComponent(jbtnConnection2ForceWin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnConnection2Disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnlConnection1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Connection 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jlblConnection1UsernameUserID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblConnection1UsernameUserID.setText("Username (User ID): 12345678");

        jlblConnection1Status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblConnection1Status.setText("Status: Lobby (cooldown)");

        jbtnConnection1Disconnect.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnConnection1Disconnect.setText("Disconnect");
        jbtnConnection1Disconnect.setPreferredSize(new java.awt.Dimension(100, 35));
        jbtnConnection1Disconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConnection1DisconnectActionPerformed(evt);
            }
        });

        jbtnConnection1ForceWin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnConnection1ForceWin.setText("Force Win");
        jbtnConnection1ForceWin.setPreferredSize(new java.awt.Dimension(100, 35));
        jbtnConnection1ForceWin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConnection1ForceWinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlConnection1Layout = new javax.swing.GroupLayout(jpnlConnection1);
        jpnlConnection1.setLayout(jpnlConnection1Layout);
        jpnlConnection1Layout.setHorizontalGroup(
            jpnlConnection1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlConnection1Layout.createSequentialGroup()
                .addGroup(jpnlConnection1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlConnection1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblConnection1UsernameUserID))
                    .addGroup(jpnlConnection1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblConnection1Status)))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlConnection1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpnlConnection1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnConnection1ForceWin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnConnection1Disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );
        jpnlConnection1Layout.setVerticalGroup(
            jpnlConnection1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlConnection1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblConnection1UsernameUserID)
                .addGap(18, 18, 18)
                .addComponent(jlblConnection1Status)
                .addGap(18, 18, 18)
                .addComponent(jbtnConnection1ForceWin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnConnection1Disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnlConnection1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnlConnection3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlConnection4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnlConnection2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlConnection1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnlConnection2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlConnection4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnlConnection3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jbtnStartStopServer, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnStartStopServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnConnection1ForceWinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConnection1ForceWinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnConnection1ForceWinActionPerformed

    private void jbtnConnection1DisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConnection1DisconnectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnConnection1DisconnectActionPerformed

    /**
     * Start the server if not running; stops it if it's running.
     */
    private void jbtnStartStopServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnStartStopServerActionPerformed
        ServerConnection server = new ServerConnection();
    }//GEN-LAST:event_jbtnStartStopServerActionPerformed

/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
                new jfServer().setVisible(true);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnConnection1Disconnect;
    private javax.swing.JButton jbtnConnection1ForceWin;
    private javax.swing.JButton jbtnConnection2Disconnect;
    private javax.swing.JButton jbtnConnection2ForceWin;
    private javax.swing.JButton jbtnConnection3Disconnect;
    private javax.swing.JButton jbtnConnection3ForceWin;
    private javax.swing.JButton jbtnConnection4Disconnect;
    private javax.swing.JButton jbtnConnection4ForceWin;
    private javax.swing.JButton jbtnStartStopServer;
    private javax.swing.JLabel jlblConnection1Status;
    private javax.swing.JLabel jlblConnection1UsernameUserID;
    private javax.swing.JLabel jlblConnection2Status;
    private javax.swing.JLabel jlblConnection2UsernameUserID;
    private javax.swing.JLabel jlblConnection3Status;
    private javax.swing.JLabel jlblConnection3UsernameUserID;
    private javax.swing.JLabel jlblConnection4Status;
    private javax.swing.JLabel jlblConnection4UsernameUserID;
    private javax.swing.JPanel jpnlConnection1;
    private javax.swing.JPanel jpnlConnection2;
    private javax.swing.JPanel jpnlConnection3;
    private javax.swing.JPanel jpnlConnection4;
    // End of variables declaration//GEN-END:variables
}
