/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foursquare;

/**
 *
 * @author jss5783
 * 
 * ----------[CHANGELOG]----------
 * 2018/04/16 -     Created. -JSS5783
 */
public class jfServer extends javax.swing.JPanel {

    /**
     * Creates new form jfServer
     */
    public jfServer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtaConsoleOutput = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jpnlConnection1 = new javax.swing.JPanel();
        jlblConnection1UsernameUserID = new javax.swing.JLabel();
        jlblConnection1Status = new javax.swing.JLabel();
        jbtnConnection1Disconnect = new javax.swing.JButton();
        jbtnConnection1ForceWin = new javax.swing.JButton();
        jpnlConnection2 = new javax.swing.JPanel();
        jlblConnection2UsernameUserID = new javax.swing.JLabel();
        jlblConnection2Status = new javax.swing.JLabel();
        jbtnConnection2Disconnect = new javax.swing.JButton();
        jbtnConnection2ForceWin = new javax.swing.JButton();

        jButton1.setText("Start Server");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 35));

        jtxtaConsoleOutput.setColumns(20);
        jtxtaConsoleOutput.setRows(5);
        jScrollPane1.setViewportView(jtxtaConsoleOutput);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Matches", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );

        jpnlConnection1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Connection 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jlblConnection1UsernameUserID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblConnection1UsernameUserID.setText("Username (User ID): 12345678");

        jlblConnection1Status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblConnection1Status.setText("Status: Lobby (cooldown)");

        jbtnConnection1Disconnect.setText("Disconnect");
        jbtnConnection1Disconnect.setPreferredSize(new java.awt.Dimension(100, 35));

        jbtnConnection1ForceWin.setText("Force Win");
        jbtnConnection1ForceWin.setPreferredSize(new java.awt.Dimension(100, 35));

        javax.swing.GroupLayout jpnlConnection1Layout = new javax.swing.GroupLayout(jpnlConnection1);
        jpnlConnection1.setLayout(jpnlConnection1Layout);
        jpnlConnection1Layout.setHorizontalGroup(
            jpnlConnection1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlConnection1Layout.createSequentialGroup()
                .addGroup(jpnlConnection1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlConnection1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jlblConnection1Status))
                    .addGroup(jpnlConnection1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jpnlConnection1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnConnection1ForceWin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnConnection1Disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnlConnection1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblConnection1UsernameUserID)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpnlConnection1Layout.setVerticalGroup(
            jpnlConnection1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlConnection1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblConnection1UsernameUserID)
                .addGap(18, 18, 18)
                .addComponent(jlblConnection1Status)
                .addGap(18, 18, 18)
                .addComponent(jbtnConnection1ForceWin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnConnection1Disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnlConnection2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Connection 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jlblConnection2UsernameUserID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblConnection2UsernameUserID.setText("Username (User ID): 12345678");

        jlblConnection2Status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblConnection2Status.setText("Status: Lobby (cooldown)");

        jbtnConnection2Disconnect.setText("Disconnect");
        jbtnConnection2Disconnect.setPreferredSize(new java.awt.Dimension(100, 35));

        jbtnConnection2ForceWin.setText("Force Win");
        jbtnConnection2ForceWin.setPreferredSize(new java.awt.Dimension(100, 35));

        javax.swing.GroupLayout jpnlConnection2Layout = new javax.swing.GroupLayout(jpnlConnection2);
        jpnlConnection2.setLayout(jpnlConnection2Layout);
        jpnlConnection2Layout.setHorizontalGroup(
            jpnlConnection2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlConnection2Layout.createSequentialGroup()
                .addGroup(jpnlConnection2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlConnection2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jlblConnection2Status))
                    .addGroup(jpnlConnection2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jpnlConnection2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnConnection2ForceWin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnConnection2Disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnlConnection2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblConnection2UsernameUserID)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpnlConnection2Layout.setVerticalGroup(
            jpnlConnection2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlConnection2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblConnection2UsernameUserID)
                .addGap(18, 18, 18)
                .addComponent(jlblConnection2Status)
                .addGap(18, 18, 18)
                .addComponent(jbtnConnection2ForceWin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnConnection2Disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpnlConnection1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jpnlConnection2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlConnection1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnlConnection2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnConnection1Disconnect;
    private javax.swing.JButton jbtnConnection1ForceWin;
    private javax.swing.JButton jbtnConnection2Disconnect;
    private javax.swing.JButton jbtnConnection2ForceWin;
    private javax.swing.JLabel jlblConnection1Status;
    private javax.swing.JLabel jlblConnection1UsernameUserID;
    private javax.swing.JLabel jlblConnection2Status;
    private javax.swing.JLabel jlblConnection2UsernameUserID;
    private javax.swing.JPanel jpnlConnection1;
    private javax.swing.JPanel jpnlConnection2;
    private javax.swing.JTextArea jtxtaConsoleOutput;
    // End of variables declaration//GEN-END:variables
}
