/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foursquare;

/**
 *
 * @author JSS5783
 * 
 * (Client) Player idles here while waiting for a match to be be made. Client can disconnect (log out) from here.
 * 
 * ----------[CHANGELOG]----------
 * 2018/04/10 -     Connected screens together (a disconnect button and [DEBUG] match button). -JSS5783
 * 
 * 2018/03/25 -     Created. -JSS5783
 */
public class jpLobby extends javax.swing.JPanel {

    /**
     * Creates new form jpLobby
     */
    public jpLobby() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnDisconnect = new javax.swing.JButton();
        jlblMessage = new javax.swing.JLabel();
        jbtnDebugGoToMatch = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(960, 540));

        jbtnDisconnect.setText("Disconnect from Server");
        jbtnDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDisconnectActionPerformed(evt);
            }
        });

        jlblMessage.setText("Searching for other person to match you against...");

        jbtnDebugGoToMatch.setText("[DEBUG] Go to Match screen");
        jbtnDebugGoToMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDebugGoToMatchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(jlblMessage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jbtnDisconnect))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(jbtnDebugGoToMatch)))
                .addContainerGap(377, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jlblMessage)
                .addGap(121, 121, 121)
                .addComponent(jbtnDisconnect)
                .addGap(42, 42, 42)
                .addComponent(jbtnDebugGoToMatch)
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Stop looking for someone to have a match with and disconnect (log out) from the server.
     * @param evt 
     */
    private void jbtnDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDisconnectActionPerformed
        jfClient.previousCard();
    }//GEN-LAST:event_jbtnDisconnectActionPerformed

    /**
     * ([EBUG] Go to match screen.
     * @param evt 
     */
    private void jbtnDebugGoToMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDebugGoToMatchActionPerformed
        jfClient.nextCard();
    }//GEN-LAST:event_jbtnDebugGoToMatchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnDebugGoToMatch;
    private javax.swing.JButton jbtnDisconnect;
    private javax.swing.JLabel jlblMessage;
    // End of variables declaration//GEN-END:variables
}
