/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foursquare;

import javax.swing.JOptionPane;

/**
 *
 * @author JSS5783
 * 
 * (Client) Player idles here while waiting for a match to be be made. Client can disconnect (log out) from here.
 * 
 * ----------[CHANGELOG]----------
 * 2018/04/23 -     Added jlblTitle. -JSS5783
 * 
 * 2018/04/18 -     Added progress bar jpbMatchmaking.
 *                  Hide jbtnDebugGoToMatch if DEBUG_MODE not enabled.
 *                  Readjusted component positioning, as it didn't want to stick for some reason. -JSS5783
 * 
 * 2018/04/16 -     Adjusted background color.
 *                  Adjusted component positioning. -JSS5783
 * 
 * 2018/04/10 -     Connected screens together (a disconnect button and [DEBUG] match button). -JSS5783
 * 
 * 2018/03/25 -     Created. -JSS5783
 */
public class jpLobby extends javax.swing.JPanel {

    /**
     * Creates new form jpLobby
     */
    public jpLobby() {
        initComponents();
        
        if (PVar.DEBUG_MODE == false)
        {
            jbtnDebugGoToMatch.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnDisconnect = new javax.swing.JButton();
        jlblMessage = new javax.swing.JLabel();
        jbtnDebugGoToMatch = new javax.swing.JButton();
        jpbMatchmaking = new javax.swing.JProgressBar();
        jlblTitle = new javax.swing.JLabel();

        setBackground(PVar.BACKGROUND_COLOR);
        setMinimumSize(new java.awt.Dimension(960, 540));

        jbtnDisconnect.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnDisconnect.setText("Disconnect from Server");
        jbtnDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDisconnectActionPerformed(evt);
            }
        });

        jlblMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblMessage.setText("Searching for other person to match you against...");

        jbtnDebugGoToMatch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnDebugGoToMatch.setText("[DEBUG] Go to Match screen");
        jbtnDebugGoToMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDebugGoToMatchActionPerformed(evt);
            }
        });

        jpbMatchmaking.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpbMatchmaking.setIndeterminate(true);

        jlblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblTitle.setText("Lobby");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 320, Short.MAX_VALUE)
                .addComponent(jlblMessage)
                .addContainerGap(329, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpbMatchmaking, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jbtnDisconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(455, 455, 455)
                .addComponent(jlblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnDebugGoToMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jlblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(jlblMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jpbMatchmaking, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jbtnDisconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnDebugGoToMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt 
     */
    /**
     * Asks the user if they want to disconnect.
     * If yes, then stop looking for someone to have a match with and disconnect (log out) from the server.
     * TODO: Figure out the custom dialog to get the default option to be "no".
     */
    private void jbtnDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDisconnectActionPerformed
        int intResult = JOptionPane.showConfirmDialog(this, "Are you sure you want to disconnect?\nYour session will be closed and you will no longer be able to update that session's score.", "Disconnect", JOptionPane.YES_NO_OPTION);
        if (intResult == JOptionPane.YES_OPTION)
        {
            jfClient.previousCard();
        }
    }//GEN-LAST:event_jbtnDisconnectActionPerformed

    /**
     * ([EBUG] Go to match screen.
     * @param evt 
     */
    private void jbtnDebugGoToMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDebugGoToMatchActionPerformed
        jfClient.nextCard();
    }//GEN-LAST:event_jbtnDebugGoToMatchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnDebugGoToMatch;
    private javax.swing.JButton jbtnDisconnect;
    private javax.swing.JLabel jlblMessage;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JProgressBar jpbMatchmaking;
    // End of variables declaration//GEN-END:variables
}
